### ISSUE TITLE
Profile page goes blank

### ISSUE THREAD

**Issue by Shaiq1217** [pinacai/pinac_web#8]
Upon opening the profile page, it goes blank. I suggest if it is still under development we should add a Coming Soon screen. This goes for all the pages still on the todo. We could create a nice fallback. Also we could add a 404 page

**Comment by RajeshTechForge** [comment]
No, it's actually a bug caused by a logical mistake that needs fixing.

**Comment by RajeshTechForge** [comment]
Yes, we need to show a coming soon screen, as the profile page design is still not ready. I would be happy if you add the coming soon screen.

**Comment by RajeshTechForge** [comment]
Solved, showing `404 not found` after shifting to Next.js
